---
# Variables listed here are applicable to all host groups

url_apt_key: "http://keyserver.ubuntu.com/pks/lookup?op=get&search="

ntpserver: 'ntp.ubuntu.com'

user: eaglescout

apache:
  httpd_port: 80
  domain: stem.local
  project_path: /home/eaglescout/dev/stem
  directory_index: app.php
  docroot: /var/www/eaglescout
  servername: localhost

php:
  php_date_timezone: 'America/New_York'
  install: '1'
  ppa: php5-5.6
  packages: [php5-dev, php5-cli, php-pear, php5-curl, php5-intl, php5-json, php5-mcrypt, php5-mysql, php5-curl, php5-imagick, php5-xdebug, php5-xmlrpc]

mariadb:
  current_password: ''
  root_password: pass@word1

mysql:
    install: '1'
    root_password: pass@word1
    database: eaglescout
    user: eaglescout
    password: eaglescout1
    dump: ''
