---
# Variables listed here are applicable to all host groups

url_apt_key: "http://keyserver.ubuntu.com/pks/lookup?op=get&search="

user: eaglescout

common:
  install: '1'
  timezone: UTC
  locale: en_US.UTF-8
  ntpserver: 'ntp.ubuntu.com'

apache:
  httpd_port: 80
  docroot: /var/www/eaglescout
  servername: localhost

php:
  php_date_timezone: 'America/New_York'
  install: '1'
  ppa: php5-5.6
  packages: [php5-dev, php5-cli, php-pear, php5-curl, php5-intl, php5-json, php5-mcrypt, php5-mysql, php5-curl, php5-imagick, php5-xdebug, php5-xmlrpc]

php7:
  php_date_timezone: 'America/New_York'
  install: '1'
  packages: [php7.0-common, php7.0-cli, libpcre3-dev, php7.0-gd, php7.0-curl, php7.0-mysql, php7.0-mcrypt, php7.0-imap, php7.0-json, php7.0-opcache, php7.0-xml, php7.0-mbstring]

mariadb:
  current_password: ''
  root_password: pass@word1

mysql:
    install: '1'
    root_password: pass@word1
    database: eaglescout
    user: eaglescout
    password: eaglescout1
    dump: ''

# Node.js configuration (if enabled above).
# Valid examples: "0.10", "0.12", "4.x", "5.x".
nodejs_version: "0.12"
nodejs_npm_global_packages: []
nodejs_install_npm_user: "ubuntu"
npm_config_prefix: "/home/ubuntu/.npm-global"
