---
# Variables listed here are applicable to all host groups

url_apt_key: "http://keyserver.ubuntu.com/pks/lookup?op=get&search="

ntpserver: 'ntp.ubuntu.com'

user: eaglescout

web:
  httpd_port: 80
  domain: stem.local
  project_path: /home/eaglescout/dev/stem
  directory_index: app.php

php5:
  php_date_timezone: 'America/New_York'

mariadb:
  current_password: ''
  root_password: dev




### IMPORTED VARS ###
---
hosts: vagrant

server:
    install: '1'
    packages: [imagemagick, curl]
    timezone: UTC
    locale: en_US.UTF-8
apache:
    install: '1'
    docroot: /var/www/eaglescout
    servername: localhost
mysql:
    install: '1'
    root_password: pass@word1
    database: live_noac2015
    user: live_noac2015
    password: GoodUrner1915
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-dev, php5-cli, php5-pear, php5-curl, php5-intl, php5-json, php5-mcrypt, php5-mysql, php5-curl, php5-imagick, php5-xdebug, php5-xmlrpc]
composer:
    install: '1'

