##
# Ansible playbook for setting up a LAMP development server on Ubuntu 14.04.
#

---

- hosts: local
  user: eaglescout
  sudo: yes

  vars_files:
    - group_vars/all.yml

  roles:
    - common       # List of essential packages
    - vim          # Configuration for vim
    - apache
    - php
    - mariadb
    - mysql
    - phpmyadmin
#    - mongodb
    - composer
    - nodejs
    - synapse      # Launcher apps.
