##
# Ansible playbook for setting up a LAMP development server on Ubuntu 20.04.
#
---

- hosts: localhost
  connection: local
  user: eaglescout
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - common
    - adriagalin.timezone
    - geerlingguy.ntp
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.mysql
    - geerlingguy.apache-php-fpm
    - geerlingguy.php-mysql
    - geerlingguy.phpmyadmin
    - geerlingguy.composer
    - geerlingguy.nodejs
