##
# Ansible playbook for setting up a LAMP development server on Ubuntu 20.04.
#
---

- hosts: local
  user: eaglescout
  become: true

  vars_files:
    - group_vars/all.yml

  roles:
    - common       # List of essential packages

    - { role: geerlingguy.apache }
    - { role: geerlingguy.php }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.apache-php-fpm }
    - { role: geerlingguy.php-mysql }
    - { role: geerlingguy.phpmyadmin }
    - { role: geerlingguy.composer }
    - { role: geerlingguy.nodejs }
