---
# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Add default username and password for MySQL connection.
  lineinfile: >
    dest=/etc/phpmyadmin/config.inc.php
    state=present
    regexp="^.+\['{{ item.key }}'\].+$"
    line="$cfg['Servers'][$i]['{{ item.key }}'] = '{{ item.value }}';"
    insertbefore="^\?>"
  with_items:
  - { key: host, value: "{{ phpmyadmin.mysql_host }}" }
  - { key: port, value: "{{ phpmyadmin.mysql_port }}" }
  - { key: socket, value: "{{ phpmyadmin.mysql_socket }}" }
  - { key: connect_type, value: "{{ phpmyadmin.mysql_connect_type }}" }
  - { key: user, value: "{{ phpmyadmin.mysql_user }}" }
  - { key: password, value: "{{ phpmyadmin.mysql_password }}"}
