---

# This role deploys the MariaDB processes and sets up settings.

- name: MariaDB | Add keys authenticity
  apt_key: id=0xcbcb082a1bb943db state=present

- name: MariaDB | Add source sources
  apt_repository: repo='deb http://nwps.ws/pub/mariadb/repo/10.0/ubuntu utopic main' update_cache=yes

- name: MariaDB | Install Packages
  apt: pkg={{ item }} state=installed
  with_items:
    - mariadb-server
    - mariadb-client
    - libmariadbclient18
    - python-mysqldb
    - python-mysql.connector
  notify: Start mariadb

- name: MariaDB | Test
  shell: ls /root/.my.cnf | wc -l
  register: database_config

- name: MariaDB | Update mysql root password for all root accounts from local servers
  mysql_user: login_user=root
              login_password={{ mariadb.current_password }}
              name=root
              host={{ item }}
              password={{ mariadb.root_password }}
              priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
#  when: database_config == 0
  notify: Restart mariadb

- name: MariaDB | Write file my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: MariaDB | Write file my.cnf
  template: src=my.cnf.j2 dest={{ ansible_env.HOME }}/.my.cnf owner={{ ansible_env.LOGNAME }} mode=0600

#- name: MariaDB | Remove the MySQL test database
#  mysql_db: db=test state=absent
