---
# This playbook contains common plays that will be run on all nodes.

# for 1.6 this ansible
- name: Create en_US.UTF-8 locale
  locale_gen: 
    name=en_US.UTF-8
    state=present

- name: Configure the timezone
  become: true
  template: 
    src=timezone.tpl 
    dest=/etc/timezone

- name: More Configure the timezone
  become: true
  file: 
    src=/usr/share/zoneinfo/{{common.timezone}}
    path=/etc/localtime 
    state=link 
    force=yes 
    backup=yes

- name: Set default system language pack
  shell: locale-gen {{common.locale}}
  become: true

- name: Linux | Update cache
  become: true
  apt: 
    update_cache=yes
    cache_valid_time={{ cache_valid_time }}

- name: Package | Install lists packages
  become: true
  apt: 
    pkg={{ item }} 
    state=installed
  with_items:
    - aptitude
    - bash-completion
    - openssh-server
    - vim
    - git
    - git-core
    - git-flow
    - git-email
    - git-extras
    - git-svn
    - zsh
    - curl
    - wget
    - htop
    - ack-grep
    - ccze
    - tmux
    - terminator
    - tig
    - unzip
    - tar
    - gzip
    - bzip2
    - nfs-kernel-server
    - nfs-common
    - pwgen
    - imagemagick
