---
- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install php5
  sudo: yes
  apt: pkg=php5 state=latest

- name: Install php5-fpm
  sudo: yes
  apt: pkg=php5-fpm state=latest

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php.packages
  when: php.packages is defined
  notify: Restart apache

- name: PHP5 | Configuration /etc/php5/apache2/php.ini
  template: src=etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini mode=0644
  notify: Restart apache

- name: PHP5 | Configuration /etc/php5/cli/php.ini
  template: src=etc-php5-cli-php-ini.j2 dest=/etc/php5/cli/php.ini mode=0644

- name: PHP5 | PHPDev | Update pear channels
  command: pear update-channels

- name: PHP5 | PHPDev | Update pear packages
  command: pear upgrade-all

- name: PHP | PHPDev | Set pear auto-discover
  command: pear config-set auto_discover 1

- name: PHP | PHPDev | Pear install the PHP QA Toolchain
  command: pear install pear.phpqatools.org/phpqatools creates=/usr/bin/phpunit
  # this fails often (dns problems, pear problems, etc. So just ignore the errors and continue.)
  ignore_errors: true

- include: configure.yml
- include: pecl.yml
